baseURL: https://zackarypryde.netlify.app/
title: Zackary Pryde
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Zackary Pryde
  description: Academic portfolio.
  menu_item_separator: '   '
  avatar: C:/Users/pryde/OneDrive/Desktop/Career/Portfolio/Portfolio3/themes/hugo-theme-m10c/static/avatar.jpg
  social:
    - icon: github
      name: GitHub
      url: https://github.com/ZackaryPryde
    - icon: linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/zack-pryde/
