---
title: Realestate value in the Cape Peninsula
author: Zackary Pryde
date: '2022-01-17'
slug: []
categories: []
tags:
  - Geospatial
  - GIS
  - R
  - Web scraping
---

## About this project

blah blah blah blah

## How?

### Step 1

### Step 2

### Step 3


## The result

```{r, include=FALSE}
# 1. Package installations ----

# install.packages("rvest")
# install.packages("dplyr")
# install.packages("tmap")
# install.packages("leaflet")
# install.packages("tmaptools")

# 2. Loading the required libraries ----

library(rvest)
library(dplyr)
library(tidyr)
library(rgdal)
library(tidyverse)
library(ggmap)
library(sf)
library(mapview)
library(tmap)
library(leaflet)
library(tmaptools)

```

```{r, include=FALSE}
CPM = st_read("CapePenMap.shp")
CPMn = st_as_sf(CPM)
CPMn = data.frame("Suburb" = CPM$NAME, "Median Price" = CPM$CP_Final2_, "No. listed" = CPM$CP_Final_1, CPM$geometry)
CPMn = st_as_sf(CPMn)
```

```{r, include=FALSE}
# P = ggplot(CPMn) + 
#   geom_sf(aes(fill = Median.Price)) + 
#   scale_fill_gradient2()
# 
# Nl = ggplot(CPMn) + 
#   geom_sf(aes(fill = No..listed)) + 
#   scale_fill_gradient2()


```

```{r, include=TRUE, eval=TRUE}
mapview(CPMn, zcol = "Median.Price")
```


